# App specific properties.
spring:
    main:
        allow-circular-references: true

aphe:
    product:
        appId: ttr
        appName: Ticket To Ride
        url: http://ttr.arutla.com

management:
    endpoints:
        web:
            base-path: /badbadbadfeed
            exposure:
                include: loggers,health,info,env,threaddump
    endpoint:
        health.show-details: always
        loggers:
            enabled: true
    info.git.mode: full