appName: ttr-qa
url: http://ttrapi-qa.arutla.com
name: Tikcet To Ride

spring:
    profiles: qa

aphe:
    auth:
        allowedHosts: http://ttr-qa.arutla.com
logging:
    file:
        name: /data/logs/ttr_qa_app