appName: ttr-prod
url: http://ttr.arutla.com
name: Tikcet To Ride

spring:
    profiles: prod

aphe:
    auth:
        allowedHosts: http://ttr.arutla.com
logging:
    file:
        name: /data/logs/ttr_prod_app
