appName: ttr-dev
url: http://ttr.local.apheliontechnologies.com
name: Ticket To Ride  - Developer Mode

spring:
    profiles: dev

aphe:
    product:
        appId: ttr-dev
        appName: Ticket To Ride - Dev
        url: http://ttr.local.arutla.com:3001
    auth:
        allowedHosts: http://ttr.local.arutla.com:4000

server:
    port: 9080

security:
   require-ssl: false

logging:
    file:
        path: "target/ttr"