appName: ttr-qa
url: https://ttrapi-qa.apheliontechnologies.com
name: Tikcet To Ride

spring:
    profiles: qa

aphe:
    auth:
        allowedHosts: https://ttr-qa.apheliontechnologies.com
logging:
    file:
        name: /usr/local/tomcat/logs/ttr-qa